apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  namespace: webapps
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer